# Generated by Django 4.1.3 on 2022-11-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='contact us',
        ),
    ]
