# Generated by Django 4.1.3 on 2022-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserauthentication',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
