# Generated by Django 4.1.3 on 2022-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_customuserauthentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserAuthentication',
        ),
    ]
