# Generated by Django 4.1.3 on 2022-11-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0005_customuserauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserauthentication',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.useraddress'),
        ),
        migrations.AlterField(
            model_name='customuserauthentication',
            name='panelty',
            field=models.IntegerField(default=0),
        ),
    ]
